# Generated by Django 5.0 on 2023-12-08 19:43

import django.db.models.deletion
import django.utils.timezone
import shared.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', shared.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('punch_date', models.DateField()),
                ('punch_time', models.TimeField()),
                ('check_in', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punching_details', to='employee.employee')),
            ],
            options={
                'db_table': 'punching',
                'unique_together': {('employee', 'punch_date', 'punch_time')},
            },
        ),
    ]
